mappings:
    a: STONE
    b: COBBLESTONE
    c: DIRT
    d: CLAY
    e: SAND
    f: GRAVEL
    g: OAK_PLANKS
    h: SPRUCE_PLANKS
    i: BIRCH_PLANKS
    j: JUNGLE_PLANKS
    k: ACACIA_PLANKS
    l: DARK_OAK_PLANKS
    m: GOLD_BLOCK
    n: IRON_BLOCK
    ñ: DIAMOND_BLOCK
    o: EMERALD_BLOCK
    p: LAPIS_BLOCK
    q: REDSTONE_BLOCK
    r: CALCITE
    s: NETHER_BRICKS
    t: BRICKS
    u: PRISMARINE
    v: END_STONE
    w: OBSIDIAN
    x: BOOKSHELF
    y: NETHERRACK
    z: SMOOTH_STONE
