name: QLTML
version: "${version}"
main: com.spectrasonic.QLTML.Main
api-version: "1.21"
authors: [Spectrasonic]
depend: [FastAsyncWorldEdit]
commands:
    qltml:
        usage: /qltml <game on|off>
        description: Comando para activar o desactivar el minijuego QLTML.

permissions:
    qltml.bypass:
        description: Permite al host del evento evitar la generación del pilar.
        default: op
