name: QLTML
version: "${version}"
main: com.spectrasonic.QLTML.Main
api-version: "1.21"
authors: [Spectrasonic]
depend: [FastAsyncWorldEdit]
commands:
    qltml:
        usage: /qltml <subcommand>
        description: Comando principal del plugin QLTML.
        permission: qltml.command

permissions:
    qltml.command:
        description: Permiso para usar el comando /qltml.
        default: true
    qltml.bypass:
        description: Permite al host del evento evitar la generación del pilar.
        default: op
    qltml.team:
        description: Permiso para usar el comando /qltml team.
        default: true
    qltml.reload:
        description: Permiso para recargar la configuración del plugin.
        default: op
